version: 2

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    branches:
      only:
        - master
    executor: android/android

    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          command: ./gradlew clean assmbleDebug